#%RAML 1.0 DataType
displayName: Cupcake
description: Representation of a Cupcake object
properties:
  cupcake_flavor:
    type: string
  cupcake_cost:
    # Again, come back and find the better data type for money.
    type: number
  cupcake_stock:
    type: integer
