package com.revature.model;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity

@Table(name = "bakery")
public class Bakery {

	/*
	 * If you have a column that has an autogenerated value, you should use two additional annotations
	 * there.
	 */
	@Id
	@Column
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "bakery_id_seq")
	@SequenceGenerator(name = "bakery_id_seq", allocationSize = 1)
	private int id;
	@Column
	private String name;
	@Column
	private String street;
	@Column
	private String state;
	@Column
	private String zipCode;
	@Column
	private String specialty;
	/*
	 * We want to create a many-to-many relationship between cupcakes and bakeries. We have
	 * chosen to manage this relationship from the bakery side. I'll first specify the relationship
	 * between the 2 entities (e.g. many to many, many to one, etc.).
	 */
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(joinColumns = {@JoinColumn(name = "bakery_id")},
	inverseJoinColumns = {@JoinColumn(name = "cupcake_flavor")})
	private Set<Cupcake> cupcakes;

	public Bakery() {
		super();
		// TODO Auto-generated constructor stub
	}

	
	public Bakery(int id, String name, String street, String state, String zipCode, String specialty,
			Set<Cupcake> cupcakes) {
		super();
		this.id = id;
		this.name = name;
		this.street = street;
		this.state = state;
		this.zipCode = zipCode;
		this.specialty = specialty;
		this.cupcakes = cupcakes;
	}


	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getSpecialty() {
		return specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	
	
	public Set<Cupcake> getCupcakes() {
		return cupcakes;
	}


	public void setCupcakes(Set<Cupcake> cupcakes) {
		this.cupcakes = cupcakes;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cupcakes == null) ? 0 : cupcakes.hashCode());
		result = prime * result + id;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((specialty == null) ? 0 : specialty.hashCode());
		result = prime * result + ((state == null) ? 0 : state.hashCode());
		result = prime * result + ((street == null) ? 0 : street.hashCode());
		result = prime * result + ((zipCode == null) ? 0 : zipCode.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Bakery other = (Bakery) obj;
		if (cupcakes == null) {
			if (other.cupcakes != null)
				return false;
		} else if (!cupcakes.equals(other.cupcakes))
			return false;
		if (id != other.id)
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (specialty == null) {
			if (other.specialty != null)
				return false;
		} else if (!specialty.equals(other.specialty))
			return false;
		if (state == null) {
			if (other.state != null)
				return false;
		} else if (!state.equals(other.state))
			return false;
		if (street == null) {
			if (other.street != null)
				return false;
		} else if (!street.equals(other.street))
			return false;
		if (zipCode == null) {
			if (other.zipCode != null)
				return false;
		} else if (!zipCode.equals(other.zipCode))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Bakery [id=" + id + ", name=" + name + ", street=" + street + ", state=" + state + ", zipCode="
				+ zipCode + ", specialty=" + specialty + ", cupcakes=" + cupcakes + "]";
	}
}
